In [2]:
import pandas as pd
import matplotlib.pyplot as plt

#read in data 
chidat = pd.read_csv("chicago_adopted_20k_Jan_20.csv") 
stldat = pd.read_csv("StL_adopted_20k_Jan_21.csv")
inddat = pd.read_csv("Indy_adopted_20k_Jan_21.csv")

petdat = pd.concat([chidat, stldat, inddat])

#drop variables that aren't interesting out of the gate

petdat = petdat.drop(['Unnamed: 0',
                      'url',
                      'type',
                      'species',
                      'tags',
                      'description',
                      'attributes.declawed',
                      'contact.phone',
                      'contact.address.address1',
                      'contact.address.address2',
                      'contact.address.state',
                      'contact.address.postcode',
                      'contact.address.country',
                      'photos',
                      'colors.primary',
                      'colors.secondary',
                      'colors.tertiary',
                      '_links.self.href',
                      '_links.type.href'], axis=1)


#drop variables that have lots of NAs, leaving only features with no NAs (well, name has 1???)

petdat = petdat.drop(['breeds.secondary',
                      'environment.children',
                      'environment.dogs',
                      'environment.cats',
                      'contact.email',
                      'coat'], axis=1)


#reformat dates and calculate difference in dates (= target variable)

fmt ='%Y-%m-%dT%H:%M:%S+0000'
petdat['published_at'] =  pd.to_datetime(petdat['published_at'], format=fmt)
petdat['status_changed_at'] =  pd.to_datetime(petdat['status_changed_at'], format=fmt)
petdat['time_diff'] = petdat['status_changed_at'] - petdat['published_at']
petdat['target_hour'] = petdat.time_diff.astype('timedelta64[h]')

petdat.head()


#take out outliers

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,organization_id,age,gender,size,name,status,status_changed_at,published_at,distance,...,breeds.mixed,breeds.unknown,attributes.spayed_neutered,attributes.house_trained,attributes.special_needs,attributes.shots_current,contact.address.city,_links.organization.href,time_diff,target_hour
0,47151520,WI463,Baby,Female,Medium,Pacey,adopted,2020-01-19 20:35:12,2020-01-19 19:37:30,62.0190,...,True,False,True,False,False,True,Racine,/v2/organizations/wi463,0 days 00:57:42,0.0
1,47150453,IL663,Baby,Female,Medium,Lola,adopted,2020-01-20 23:30:53,2020-01-19 14:28:50,37.9186,...,True,False,True,True,False,True,Hainesville,/v2/organizations/il663,1 days 09:02:03,33.0
2,47148767,IL782,Adult,Female,Medium,Mama Mia,adopted,2020-01-19 14:26:53,2020-01-18 21:33:03,35.4803,...,True,False,False,False,False,False,Joliet,/v2/organizations/il782,0 days 16:53:50,16.0
3,47147717,WI13,Young,Male,Medium,Mason- PS,adopted,2020-01-18 22:35:29,2020-01-18 18:35:31,78.8180,...,False,False,False,False,False,True,West Milwaukee,/v2/organizations/wi13,0 days 03:59:58,3.0
4,47146215,IL496,Young,Male,Medium,Speedo,adopted,2020-01-18 18:09:29,2020-01-18 03:50:20,7.2643,...,False,False,True,False,False,True,Chicago,/v2/organizations/il496,0 days 14:19:09,14.0